"""
Pydantic schemas for the 2026 Agentic AI Multi-Agent Clinical Triage Engine.
"""

from __future__ import annotations

from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class LesionHallmark(BaseModel):
    """Specific retinal lesion detected via XAI activation analysis."""
    name: str = Field(..., description="Name of lesion type (e.g., Microaneurysms, Blot Hemorrhages)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in lesion hallmark presence")
    severity: str = Field(..., description="Mild | Moderate | Severe")
    quadrants_affected: int = Field(default=1, ge=1, le=4, description="ETDRS 4-quadrant count")
    clinical_note: str = Field(..., description="Clinical significance in ETDRS grading")


class Agent1TriageOutput(BaseModel):
    """Output from Agent 1: Clinical Triage Specialist."""
    agent_name: str = Field(default="Agent 1: Clinical Triage Specialist")
    status: str = Field(default="COMPLETED")
    image_quality_grade: str = Field(..., description="Optimal | Diagnostic | Suboptimal")
    blur_score: float = Field(..., description="Laplacian sharpness metric")
    contrast_score: float = Field(..., description="Pixel luminance standard deviation")
    lesions_detected: List[LesionHallmark] = Field(default_factory=list)
    optic_disc_visibility: str = Field(default="Clear", description="Clear | Obscured")
    macular_involvement: bool = Field(default=False, description="Macular edema or exudates suspected")
    summary: str = Field(..., description="Triage assessment summary")


class DiagnosticDifferential(BaseModel):
    """Individual differential diagnosis candidate."""
    stage: str = Field(..., description="ICDR DR stage")
    probability: float = Field(..., description="Model calibrated probability")
    icd10_code: str = Field(..., description="World Health Organization ICD-10 code")


class Agent2PathologyOutput(BaseModel):
    """Output from Agent 2: Diagnostic & Staging Specialist."""
    agent_name: str = Field(default="Agent 2: Diagnostic & Staging Specialist")
    status: str = Field(default="COMPLETED")
    primary_icdr_stage: str = Field(..., description="Final staged ICDR grade")
    icd10_code: str = Field(..., description="Primary ICD-10 diagnostic code")
    conformal_coverage_set: List[str] = Field(
        ..., description="Mathematically guaranteed 95% conformal prediction set"
    )
    etdrs_progression_risk: str = Field(..., description="Low (<5%) | Moderate (15-25%) | High (>50%) 1-year progression risk")
    differential_diagnosis: List[DiagnosticDifferential] = Field(default_factory=list)
    clinical_rationale: str = Field(..., description="Pathological basis for ICDR grade")


class SafetyCheck(BaseModel):
    """Individual clinical protocol safety checkpoint."""
    criterion: str = Field(..., description="Safety check name")
    passed: bool = Field(..., description="Whether the check passed safety bounds")
    details: str = Field(..., description="Check findings or warning notes")


class Agent3AuditorOutput(BaseModel):
    """Output from Agent 3: Safety & Referral Protocol Auditor."""
    agent_name: str = Field(default="Agent 3: Safety & Referral Protocol Auditor")
    status: str = Field(default="COMPLETED")
    referral_urgency: str = Field(
        ..., description="Emergency (Within 48h) | Urgent (2-4 Weeks) | Semi-Urgent (2-3 Months) | Routine (6-12 Months)"
    )
    recommended_interventions: List[str] = Field(default_factory=list)
    safety_checks: List[SafetyCheck] = Field(default_factory=list)
    contraindications_or_warnings: List[str] = Field(default_factory=list)
    regulatory_disclaimer: str = Field(
        default="AI screening decision support only. Clinical examination by an ophthalmologist required prior to any treatment intervention."
    )


class MultiAgentConsensusReport(BaseModel):
    """Final synthesized clinical consultation generated by the agentic multi-agent loop."""
    consensus_reached: bool = Field(default=True)
    consensus_status: str = Field(
        default="UNANIMOUS_AGREEMENT",
        description="UNANIMOUS_AGREEMENT | MAJORITY_STAGED | ESCALATED_FOR_MANUAL_REVIEW"
    )
    triage_agent: Agent1TriageOutput
    pathology_agent: Agent2PathologyOutput
    safety_auditor: Agent3AuditorOutput
    synthesized_recommendation: str = Field(..., description="Executive summary for the healthcare worker / ophthalmologist")
